/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as SongRouteImport } from './routes/song'
import { Route as LittleThingsRouteImport } from './routes/little-things'
import { Route as IndexRouteImport } from './routes/index'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const SongRoute = SongRouteImport.update({
  id: '/song',
  path: '/song',
  getParentRoute: () => rootRouteImport,
} as any)
const LittleThingsRoute = LittleThingsRouteImport.update({
  id: '/little-things',
  path: '/little-things',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/little-things': typeof LittleThingsRoute
  '/song': typeof SongRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/little-things': typeof LittleThingsRoute
  '/song': typeof SongRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/little-things': typeof LittleThingsRoute
  '/song': typeof SongRoute
  '/why': typeof WhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/little-things' | '/song' | '/why'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/little-things' | '/song' | '/why'
  id: '__root__' | '/' | '/little-things' | '/song' | '/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LittleThingsRoute: typeof LittleThingsRoute
  SongRoute: typeof SongRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song': {
      id: '/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof SongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/little-things': {
      id: '/little-things'
      path: '/little-things'
      fullPath: '/little-things'
      preLoaderRoute: typeof LittleThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LittleThingsRoute: LittleThingsRoute,
  SongRoute: SongRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
